from .login import *
from .techer_views import *
from .student_views import *
from .group_views import *
from .attendance_views import *
from .statistic_views import *
from .homework_views import *
from .payment_views import *
from .lesson_views import *